server:
  port: 8092
  servlet:
    context-path: /qinfa-platform-uaa
spring:
  application:
    name: qinfa-platform-uaa
  redis:
    database: 12
    host: 121.33.190.195
    port: 6379
    password: bdntestpasswd
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
management:
  endpoint:
    health:
      enabled: true