server:
  port: 8088
spring:
  application:
    name: qinfa-platform-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      ## \u5168\u5C40\u8DE8\u57DF\u914D\u7F6E
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: '*'
            allowed-headers: '*'
            allowed-methods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
              - HEAD
              - PATCH
            max-age: 3600
        add-to-simple-url-handler-mapping: true
      ## \u8DEF\u7531\u914D\u7F6E
      routes:
        - id: qinfa-platform-coal-mine
          uri: lb://qinfa-platform-coal-mine
          predicates:
            - Path=/api/coal-mine/**
          filters:
            - RewritePath=/api/coal-mine/(?<segment>/?.*), /qinfa-platform-coal-mine/$\{segment}
        - id: qinfa-platform-admin-route
          uri: lb://qinfa-platform-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /qinfa-platform-admin/$\{segment}
  # \u8BBE\u7F6E\u5927\u6587\u4EF6\u5927\u5C0F\u9650\u5236
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
