server:
  port: 8088
spring:
  application:
    name: qinfa-platform-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: qinfa-platform
          uri: /qinfa-platform-admin