server:
  port: 8091
  servlet:
    context-path: /qinfa-platform-generator
# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.33.190.195:48366/qf_coal_mine?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: cli_users
    password: KJDjifdf343A

  resources:
    # 关闭工程中的资源文件建立映射
    add-mappings: false
  # 接口处理器不存在即抛异常
  mvc:
    throw-exception-if-no-handler-found: true
# mybatis
mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
# 分页
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

